export const FRASES: string[] = [
  "No compito con nadie más. Solo con quien fui ayer.",
  "Cada hábito que cultivas hoy te convierte en quien querías ser mañana.",
  "Tu constancia habla más fuerte que tu motivación.",
  "Pequeños pasos cada día suman una vida extraordinaria.",
  "El progreso no siempre es visible, pero siempre es real cuando actúas con intención.",
  "Dios tiene un plan para ti. Tu parte es mostrarte cada día.",
  "La disciplina es la forma más alta de amor propio.",
  "No necesitas ser perfecta. Solo necesitas ser constante.",
  "Cada mañana que te levantas con intención, ganas la mitad de la batalla.",
  "Tu cuerpo es templo. Tu mente es jardín. Cuida ambos con amor.",
  "El descanso también es productividad. Recárgarte es prepararte.",
  "Una mujer que conoce su valor no busca validación. La irradia.",
  "Tus victorias pequeñas merecen celebrarse tanto como las grandes.",
  "No hay meta pequeña cuando viene de un corazón grande.",
  "La gratitud no cambia lo que tienes — cambia cómo lo ves.",
  "Cuando dudas, ora. Cuando estás perdida, ora. Cuando estás bien, ora también.",
  "Tu historia no terminó. Hay páginas en blanco esperando tu pluma.",
  "La versión de ti que sueñas ya existe — solo necesitas caminar hacia ella.",
  "El caos exterior se calma cuando hay orden interior.",
  "No pospongas la vida que quieres por miedo a la que tienes.",
  "Eres exactamente lo suficiente. Y también puedes crecer.",
  "La fe no elimina el trabajo duro — lo hace con propósito.",
  "Tu energía es tu recurso más valioso. Inviértela en lo que te eleva.",
  "No tienes que tenerlo todo claro para dar el siguiente paso.",
  "Lo que practicas en privado se convierte en quién eres en público.",
  "Hoy es el día que pusiste en tus metas del mes pasado.",
  "Mereces la misma energía que le das a los demás.",
  "Una mente en paz atrae lo que una mente en caos ahuyenta.",
  "Tus emociones son válidas. Tus reacciones son una elección.",
  "Sanar no es lineal, pero cada día que decides intentarlo cuenta.",
  "La mujer que cuida su cuerpo cuida también su visión.",
  "Empieza donde estás. Usa lo que tienes. Haz lo que puedas.",
  "No hay mejor inversión que invertir en quien ves en el espejo.",
  "La paciencia no es esperar — es confiar mientras actúas.",
  "Tu mente cree lo que te repites. Cuida lo que te dices.",
  "El orden no es rigidez. Es la libertad de saber qué viene después.",
  "Cada noche que cierras ojos con agradecimiento, mañana amanece con propósito.",
  "No siempre puedes controlar lo que pasa. Sí puedes controlar cómo respondes.",
  "El trabajo que haces cuando nadie mira es el que más te transforma.",
  "Eres la protagonista, no la secundaria, de tu propia historia.",
  "No es cuántas veces caíste. Es cuántas veces te levantaste con más determinación.",
  "Tu bienestar no es un lujo. Es una necesidad y una responsabilidad.",
  "La consistencia supera al talento cuando el talento no es consistente.",
  "Confía en el proceso aunque no puedas ver el resultado todavía.",
  "Una vida con propósito no se improvisa — se intenciona cada día.",
  "Eres digna de todo lo que sueñas. Ahora ve por ello.",
  "El miedo y el coraje coexisten. La valentía es actuar a pesar del miedo.",
  "Rodéate de quienes celebran tu crecimiento, no de quienes temen tu luz.",
  "Tu paz interior es más valiosa que cualquier opinión externa.",
  "Cada versión de ti que ha existido merece respeto. Esta también.",
]
